language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99
  - ./make_external.sh

script:
  - python setup_tests.py
  - python -m unittest discover ./test

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
