language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

script:
  - autoreconf -fi
  - ./configure
  - make -j
# - cd ./test && python -m unittest discover

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
