language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

script:
  - sh -x install_deps.sh
  - sh -x build_third_party.sh
  - ./autogen.sh
  - ./configure
  - make -j
  - cd test
  - python test.py default_tcp
  - python test.py ledbat
  - python test.py pcc
  # - python test.py verus
  # - python test.py quic

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
